# BVN-specific configs
[eth]
block_delay = 4
max_block_delta = 5000
chain_id = 1
gateway = ""
signer_keystore = "/home/ubuntu/.bvnd/eth-ks/signer.json"
signer_passphrase = ""
validator_address = ""
poll_interval = 1
max_priority_fee_per_gas_gwei = 2

[eth.contract_address]
celr = "0x4F9254C83EB525f9FCf346490bbb3ed28a81C667"
staking = "0x8a4B4C2aCAdeAa7206Df96F00052e41d74a015CE"
staking_reward = "0xb01fd7Bc0B3c433e313bf92daC09FF3942212b42"
govern = "0xea129aE043C4cB73DcB241AAA074F9E667641BA0"
viewer = "0x5803457E3074E727FA7F9aED60454bf2F127853b"
bvn = "0x2952a3C896C81234CB5Fc9017621Ed7b2a692dC5"

[log]
color = false
level = "debug"

[bvnd]
base_gas_price = 0
chain_id = "bvn"
gas_adjustment = 1.5
keyring_backend = "file"
node_uri = "tcp://localhost:26657"
passphrase = ""
transactors = []
validator_account = ""
# validator_report_endpoint = ""
check_syncer_power = true
query_info_data_host = "appsdkv3.brevis.network:443"
host_in_ssl = true

[bvnd.check_interval]
slash = 2
brevis = 1
verifier = 1
contracts = 1
sig_wait_blk = 2
new_syncer_wait_blk = 2
